//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuno.Libreria.EmpleadoWind.ProxyWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados", Namespace="http://schemas.datacontract.org/2004/07/Neptuno.Libreria.ServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Empleados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyWCF.IEmpleadoServicio")]
    public interface IEmpleadoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoListar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoListarResponse")]
        Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados[] EmpleadoListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoListar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoListarResponse")]
        System.Threading.Tasks.Task<Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados[]> EmpleadoListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoBuscar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoBuscarResponse")]
        Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados EmpleadoBuscar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoBuscar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoBuscarResponse")]
        System.Threading.Tasks.Task<Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados> EmpleadoBuscarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoAdicionar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoAdicionarResponse")]
        string EmpleadoAdicionar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoAdicionar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoAdicionarResponse")]
        System.Threading.Tasks.Task<string> EmpleadoAdicionarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoActualizar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoActualizarResponse")]
        string EmpleadoActualizar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoActualizar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoActualizarResponse")]
        System.Threading.Tasks.Task<string> EmpleadoActualizarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoEliminar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoEliminarResponse")]
        string EmpleadoEliminar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/EmpleadoEliminar", ReplyAction="http://tempuri.org/IEmpleadoServicio/EmpleadoEliminarResponse")]
        System.Threading.Tasks.Task<string> EmpleadoEliminarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServicioChannel : Neptuno.Libreria.EmpleadoWind.ProxyWCF.IEmpleadoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServicioClient : System.ServiceModel.ClientBase<Neptuno.Libreria.EmpleadoWind.ProxyWCF.IEmpleadoServicio>, Neptuno.Libreria.EmpleadoWind.ProxyWCF.IEmpleadoServicio {
        
        public EmpleadoServicioClient() {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados[] EmpleadoListar() {
            return base.Channel.EmpleadoListar();
        }
        
        public System.Threading.Tasks.Task<Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados[]> EmpleadoListarAsync() {
            return base.Channel.EmpleadoListarAsync();
        }
        
        public Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados EmpleadoBuscar(int id) {
            return base.Channel.EmpleadoBuscar(id);
        }
        
        public System.Threading.Tasks.Task<Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados> EmpleadoBuscarAsync(int id) {
            return base.Channel.EmpleadoBuscarAsync(id);
        }
        
        public string EmpleadoAdicionar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoAdicionar(emp);
        }
        
        public System.Threading.Tasks.Task<string> EmpleadoAdicionarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoAdicionarAsync(emp);
        }
        
        public string EmpleadoActualizar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoActualizar(emp);
        }
        
        public System.Threading.Tasks.Task<string> EmpleadoActualizarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoActualizarAsync(emp);
        }
        
        public string EmpleadoEliminar(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoEliminar(emp);
        }
        
        public System.Threading.Tasks.Task<string> EmpleadoEliminarAsync(Neptuno.Libreria.EmpleadoWind.ProxyWCF.Empleados emp) {
            return base.Channel.EmpleadoEliminarAsync(emp);
        }
    }
}
